version: '3'
services:
  tinykv:
    image: tinykv-server
    container_name: tinykv
      #  network_mode: "host"  # ✅ 使用 host 网络
    entrypoint: [ "sh", "-c", 'exec /usr/local/bin/tinykv-server -scheduler 192.168.2.18:2379 -addr $(hostname -i):20160' ]

  tinykv2:
    image: tinykv-server
    container_name: tinykv2
      #  network_mode: "host"  # ✅ 使用 host 网络
    entrypoint: [ "sh", "-c", 'exec /usr/local/bin/tinykv-server -scheduler 192.168.2.18:2379 -addr $(hostname -i):20160' ]

  tinykv3:
    image: tinykv-server
    container_name: tinykv3
      #  network_mode: "host"  # ✅ 使用 host 网络
    entrypoint: [ "sh", "-c", 'exec /usr/local/bin/tinykv-server -scheduler 192.168.2.18:2379 -addr $(hostname -i):20160' ]
  tinykv4:
    image: tinykv-server
    container_name: tinykvr4
      #  network_mode: "host"  # ✅ 使用 host 网络
    entrypoint: [ "sh", "-c", 'exec /usr/local/bin/tinykv-server -scheduler 192.168.2.18:2379 -addr $(hostname -i):20160' ]
  tinykv5:
    image: tinykv-server
    container_name: tinykv5
      #  network_mode: "host"  # ✅ 使用 host 网络
    entrypoint: [ "sh", "-c", 'exec /usr/local/bin/tinykv-server -scheduler 192.168.2.18:2379 -addr $(hostname -i):20160' ]
networks:
  tinykv-net:

